// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: CurrentMonitor

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_BorderFULL = NULL;lv_obj_t *ui_TOPsection = NULL;lv_obj_t *ui_Signal_container = NULL;lv_obj_t *ui_SignalLOST = NULL;lv_obj_t *ui_SignalAntena = NULL;lv_obj_t *ui_Signal20percent = NULL;lv_obj_t *ui_Signal40percent = NULL;lv_obj_t *ui_Signal60percent = NULL;lv_obj_t *ui_Signal80percent = NULL;lv_obj_t *ui_Signal100percent = NULL;lv_obj_t *ui_Battery_container = NULL;lv_obj_t *ui_BatteryBODY = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_BatteryTIP = NULL;lv_obj_t *ui_UPtime = NULL;lv_obj_t *ui_BOTTOMsection = NULL;lv_obj_t *ui_BottomINFOFullLoad = NULL;lv_obj_t *ui_ButtomINFOSinglePhase = NULL;lv_obj_t *ui_Version = NULL;lv_obj_t *ui_MGtools = NULL;lv_obj_t *ui_ThreePhaseWINDOW = NULL;lv_obj_t *ui_ThreePhaseKVA = NULL;lv_obj_t *ui_L1KVA = NULL;lv_obj_t *ui_L2KVA = NULL;lv_obj_t *ui_L3KVA = NULL;lv_obj_t *ui_ThreePhaseAMPS = NULL;lv_obj_t *ui_L1AMPS = NULL;lv_obj_t *ui_L2AMPS = NULL;lv_obj_t *ui_L3AMPS = NULL;lv_obj_t *ui_SinglePhaseWINDOW = NULL;lv_obj_t *ui_ThreePhasesFullAMPS = NULL;lv_obj_t *ui_ThreePhasesFullKVA = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BorderFULL = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_BorderFULL);
lv_obj_set_width( ui_BorderFULL, 240);
lv_obj_set_height( ui_BorderFULL, 240);
lv_obj_set_align( ui_BorderFULL, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_BorderFULL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BorderFULL, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BorderFULL, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BorderFULL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BorderFULL, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BorderFULL, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TOPsection = lv_obj_create(ui_BorderFULL);
lv_obj_remove_style_all(ui_TOPsection);
lv_obj_set_width( ui_TOPsection, 240);
lv_obj_set_height( ui_TOPsection, 30);
lv_obj_set_align( ui_TOPsection, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_TOPsection, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_TOPsection, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TOPsection, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TOPsection, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_TOPsection, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Signal_container = lv_obj_create(ui_TOPsection);
lv_obj_remove_style_all(ui_Signal_container);
lv_obj_set_width( ui_Signal_container, 240);
lv_obj_set_height( ui_Signal_container, 30);
lv_obj_set_align( ui_Signal_container, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Signal_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SignalLOST = lv_label_create(ui_Signal_container);
lv_obj_set_width( ui_SignalLOST, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SignalLOST, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SignalLOST, 96 );
lv_obj_set_y( ui_SignalLOST, 0 );
lv_obj_set_align( ui_SignalLOST, LV_ALIGN_CENTER );
lv_label_set_text(ui_SignalLOST,"N/C");
lv_obj_add_flag( ui_SignalLOST, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_SignalLOST, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SignalLOST, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SignalLOST, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SignalLOST, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SignalAntena = lv_obj_create(ui_Signal_container);
lv_obj_remove_style_all(ui_SignalAntena);
lv_obj_set_width( ui_SignalAntena, 34);
lv_obj_set_height( ui_SignalAntena, 24);
lv_obj_set_x( ui_SignalAntena, 96 );
lv_obj_set_y( ui_SignalAntena, 0 );
lv_obj_set_align( ui_SignalAntena, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SignalAntena,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SignalAntena, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_remove_flag( ui_SignalAntena, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Signal20percent = lv_obj_create(ui_SignalAntena);
lv_obj_set_width( ui_Signal20percent, 6);
lv_obj_set_height( ui_Signal20percent, 8);
lv_obj_set_x( ui_Signal20percent, 0 );
lv_obj_set_y( ui_Signal20percent, -3 );
lv_obj_set_align( ui_Signal20percent, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_Signal20percent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Signal20percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Signal20percent, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Signal20percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Signal20percent, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Signal20percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Signal20percent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Signal20percent, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Signal40percent = lv_obj_create(ui_SignalAntena);
lv_obj_set_width( ui_Signal40percent, 6);
lv_obj_set_height( ui_Signal40percent, 12);
lv_obj_set_x( ui_Signal40percent, 0 );
lv_obj_set_y( ui_Signal40percent, -3 );
lv_obj_set_align( ui_Signal40percent, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_Signal40percent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Signal40percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Signal40percent, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Signal40percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Signal40percent, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Signal40percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Signal40percent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Signal40percent, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Signal60percent = lv_obj_create(ui_SignalAntena);
lv_obj_set_width( ui_Signal60percent, 6);
lv_obj_set_height( ui_Signal60percent, 16);
lv_obj_set_x( ui_Signal60percent, 0 );
lv_obj_set_y( ui_Signal60percent, -3 );
lv_obj_set_align( ui_Signal60percent, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_Signal60percent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Signal60percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Signal60percent, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Signal60percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Signal60percent, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Signal60percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Signal60percent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Signal60percent, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Signal80percent = lv_obj_create(ui_SignalAntena);
lv_obj_set_width( ui_Signal80percent, 6);
lv_obj_set_height( ui_Signal80percent, 20);
lv_obj_set_x( ui_Signal80percent, 0 );
lv_obj_set_y( ui_Signal80percent, -3 );
lv_obj_set_align( ui_Signal80percent, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_Signal80percent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Signal80percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Signal80percent, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Signal80percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Signal80percent, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Signal80percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Signal80percent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Signal80percent, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Signal100percent = lv_obj_create(ui_SignalAntena);
lv_obj_set_width( ui_Signal100percent, 6);
lv_obj_set_height( ui_Signal100percent, 24);
lv_obj_set_x( ui_Signal100percent, 0 );
lv_obj_set_y( ui_Signal100percent, -3 );
lv_obj_set_align( ui_Signal100percent, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Signal100percent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Signal100percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Signal100percent, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Signal100percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Signal100percent, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Signal100percent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Signal100percent, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Signal100percent, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery_container = lv_obj_create(ui_TOPsection);
lv_obj_remove_style_all(ui_Battery_container);
lv_obj_set_width( ui_Battery_container, 240);
lv_obj_set_height( ui_Battery_container, 30);
lv_obj_set_align( ui_Battery_container, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Battery_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatteryBODY = lv_obj_create(ui_Battery_container);
lv_obj_remove_style_all(ui_BatteryBODY);
lv_obj_set_width( ui_BatteryBODY, 36);
lv_obj_set_height( ui_BatteryBODY, 20);
lv_obj_set_x( ui_BatteryBODY, -95 );
lv_obj_set_y( ui_BatteryBODY, 0 );
lv_obj_set_align( ui_BatteryBODY, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_BatteryBODY, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BatteryBODY, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BatteryBODY, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BatteryBODY, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BatteryBODY, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BatteryBODY, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_BatteryBODY);
lv_bar_set_value(ui_Bar1,100,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 34);
lv_obj_set_height( ui_Bar1, 18);
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar1, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x0CFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar1, lv_obj_get_style_pad_right(ui_Bar1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_BatteryTIP = lv_obj_create(ui_Battery_container);
lv_obj_remove_style_all(ui_BatteryTIP);
lv_obj_set_width( ui_BatteryTIP, 4);
lv_obj_set_height( ui_BatteryTIP, 6);
lv_obj_set_x( ui_BatteryTIP, -76 );
lv_obj_set_y( ui_BatteryTIP, 0 );
lv_obj_set_align( ui_BatteryTIP, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_BatteryTIP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BatteryTIP, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BatteryTIP, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BatteryTIP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BatteryTIP, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BatteryTIP, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UPtime = lv_label_create(ui_TOPsection);
lv_obj_set_width( ui_UPtime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UPtime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UPtime, LV_ALIGN_CENTER );
lv_label_set_text(ui_UPtime,"00:12:56");
lv_obj_set_style_text_color(ui_UPtime, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_UPtime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_UPtime, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_UPtime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_UPtime, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BOTTOMsection = lv_obj_create(ui_BorderFULL);
lv_obj_remove_style_all(ui_BOTTOMsection);
lv_obj_set_width( ui_BOTTOMsection, 240);
lv_obj_set_height( ui_BOTTOMsection, 40);
lv_obj_set_align( ui_BOTTOMsection, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_BOTTOMsection, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_BOTTOMsection, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BOTTOMsection, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BOTTOMsection, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BOTTOMsection, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BottomINFOFullLoad = lv_label_create(ui_BOTTOMsection);
lv_obj_set_width( ui_BottomINFOFullLoad, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BottomINFOFullLoad, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BottomINFOFullLoad, LV_ALIGN_CENTER );
lv_label_set_text(ui_BottomINFOFullLoad,"SHORT press - Single Phase\nLONG press - turn OFF");
lv_obj_add_flag( ui_BottomINFOFullLoad, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_BottomINFOFullLoad, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BottomINFOFullLoad, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BottomINFOFullLoad, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BottomINFOFullLoad, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtomINFOSinglePhase = lv_label_create(ui_BOTTOMsection);
lv_obj_set_width( ui_ButtomINFOSinglePhase, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ButtomINFOSinglePhase, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ButtomINFOSinglePhase, LV_ALIGN_CENTER );
lv_label_set_text(ui_ButtomINFOSinglePhase,"SHORT press - Full Load\nLONG press - turn OFF");
lv_obj_set_style_text_color(ui_ButtomINFOSinglePhase, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtomINFOSinglePhase, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ButtomINFOSinglePhase, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ButtomINFOSinglePhase, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Version = lv_label_create(ui_BOTTOMsection);
lv_obj_set_width( ui_Version, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Version, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Version, -5 );
lv_obj_set_y( ui_Version, 0 );
lv_obj_set_align( ui_Version, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_Version,"V1.33.7");
lv_obj_set_style_text_color(ui_Version, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Version, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Version, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MGtools = lv_label_create(ui_BorderFULL);
lv_obj_set_width( ui_MGtools, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MGtools, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MGtools, 173 );
lv_obj_set_y( ui_MGtools, 75 );
lv_obj_set_align( ui_MGtools, LV_ALIGN_CENTER );
lv_label_set_text(ui_MGtools,"MG  tools");
lv_obj_set_style_text_color(ui_MGtools, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MGtools, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MGtools, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MGtools, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_MGtools, 2700, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThreePhaseWINDOW = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ThreePhaseWINDOW);
lv_obj_set_width( ui_ThreePhaseWINDOW, 236);
lv_obj_set_height( ui_ThreePhaseWINDOW, 162);
lv_obj_set_x( ui_ThreePhaseWINDOW, 0 );
lv_obj_set_y( ui_ThreePhaseWINDOW, 34 );
lv_obj_set_align( ui_ThreePhaseWINDOW, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ThreePhaseWINDOW, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ThreePhaseWINDOW, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ThreePhaseKVA = lv_obj_create(ui_ThreePhaseWINDOW);
lv_obj_remove_style_all(ui_ThreePhaseKVA);
lv_obj_set_width( ui_ThreePhaseKVA, 118);
lv_obj_set_height( ui_ThreePhaseKVA, 162);
lv_obj_set_align( ui_ThreePhaseKVA, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_ThreePhaseKVA,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ThreePhaseKVA, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_remove_flag( ui_ThreePhaseKVA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_ThreePhaseKVA, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ThreePhaseKVA, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ThreePhaseKVA, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ThreePhaseKVA, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L1KVA = lv_label_create(ui_ThreePhaseKVA);
lv_obj_set_width( ui_L1KVA, 110);
lv_obj_set_height( ui_L1KVA, 30);
lv_obj_set_align( ui_L1KVA, LV_ALIGN_CENTER );
lv_label_set_text(ui_L1KVA,"2.96 KVA");
lv_obj_set_style_text_color(ui_L1KVA, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L1KVA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L1KVA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L1KVA, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L2KVA = lv_label_create(ui_ThreePhaseKVA);
lv_obj_set_width( ui_L2KVA, 110);
lv_obj_set_height( ui_L2KVA, 30);
lv_obj_set_align( ui_L2KVA, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_L2KVA,"2.42 KVA");
lv_obj_set_style_text_color(ui_L2KVA, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L2KVA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L2KVA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L2KVA, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L3KVA = lv_label_create(ui_ThreePhaseKVA);
lv_obj_set_width( ui_L3KVA, 110);
lv_obj_set_height( ui_L3KVA, 30);
lv_obj_set_align( ui_L3KVA, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_L3KVA,"3.94 KVA");
lv_obj_set_style_text_color(ui_L3KVA, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L3KVA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L3KVA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L3KVA, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThreePhaseAMPS = lv_obj_create(ui_ThreePhaseWINDOW);
lv_obj_remove_style_all(ui_ThreePhaseAMPS);
lv_obj_set_width( ui_ThreePhaseAMPS, 118);
lv_obj_set_height( ui_ThreePhaseAMPS, 162);
lv_obj_set_flex_flow(ui_ThreePhaseAMPS,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ThreePhaseAMPS, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_remove_flag( ui_ThreePhaseAMPS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_ThreePhaseAMPS, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ThreePhaseAMPS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ThreePhaseAMPS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ThreePhaseAMPS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L1AMPS = lv_label_create(ui_ThreePhaseAMPS);
lv_obj_set_width( ui_L1AMPS, 110);
lv_obj_set_height( ui_L1AMPS, 30);
lv_obj_set_align( ui_L1AMPS, LV_ALIGN_CENTER );
lv_label_set_text(ui_L1AMPS,"L1 : 12.75 A");
lv_obj_set_style_text_color(ui_L1AMPS, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L1AMPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L1AMPS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L1AMPS, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L2AMPS = lv_label_create(ui_ThreePhaseAMPS);
lv_obj_set_width( ui_L2AMPS, 110);
lv_obj_set_height( ui_L2AMPS, 30);
lv_obj_set_align( ui_L2AMPS, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_L2AMPS,"L2 : 8.64 A");
lv_obj_set_style_text_color(ui_L2AMPS, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L2AMPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L2AMPS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L2AMPS, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_L3AMPS = lv_label_create(ui_ThreePhaseAMPS);
lv_obj_set_width( ui_L3AMPS, 110);
lv_obj_set_height( ui_L3AMPS, 30);
lv_obj_set_align( ui_L3AMPS, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_L3AMPS,"L3 : 16.66 A");
lv_obj_set_style_text_color(ui_L3AMPS, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_L3AMPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_L3AMPS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_L3AMPS, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SinglePhaseWINDOW = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_SinglePhaseWINDOW);
lv_obj_set_width( ui_SinglePhaseWINDOW, 236);
lv_obj_set_height( ui_SinglePhaseWINDOW, 162);
lv_obj_set_x( ui_SinglePhaseWINDOW, 0 );
lv_obj_set_y( ui_SinglePhaseWINDOW, 34 );
lv_obj_set_align( ui_SinglePhaseWINDOW, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_SinglePhaseWINDOW,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SinglePhaseWINDOW, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_remove_flag( ui_SinglePhaseWINDOW, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ThreePhasesFullAMPS = lv_label_create(ui_SinglePhaseWINDOW);
lv_obj_set_width( ui_ThreePhasesFullAMPS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ThreePhasesFullAMPS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ThreePhasesFullAMPS, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ThreePhasesFullAMPS,"43.75 A");
lv_obj_set_style_text_color(ui_ThreePhasesFullAMPS, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ThreePhasesFullAMPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ThreePhasesFullAMPS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ThreePhasesFullAMPS, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThreePhasesFullKVA = lv_label_create(ui_SinglePhaseWINDOW);
lv_obj_set_width( ui_ThreePhasesFullKVA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ThreePhasesFullKVA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ThreePhasesFullKVA, LV_ALIGN_CENTER );
lv_label_set_text(ui_ThreePhasesFullKVA,"14.25 KVA");
lv_obj_set_style_text_color(ui_ThreePhasesFullKVA, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ThreePhasesFullKVA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ThreePhasesFullKVA, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ThreePhasesFullKVA, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_BorderFULL= NULL;
ui_TOPsection= NULL;
ui_Signal_container= NULL;
ui_SignalLOST= NULL;
ui_SignalAntena= NULL;
ui_Signal20percent= NULL;
ui_Signal40percent= NULL;
ui_Signal60percent= NULL;
ui_Signal80percent= NULL;
ui_Signal100percent= NULL;
ui_Battery_container= NULL;
ui_BatteryBODY= NULL;
ui_Bar1= NULL;
ui_BatteryTIP= NULL;
ui_UPtime= NULL;
ui_BOTTOMsection= NULL;
ui_BottomINFOFullLoad= NULL;
ui_ButtomINFOSinglePhase= NULL;
ui_Version= NULL;
ui_MGtools= NULL;
ui_ThreePhaseWINDOW= NULL;
ui_ThreePhaseKVA= NULL;
ui_L1KVA= NULL;
ui_L2KVA= NULL;
ui_L3KVA= NULL;
ui_ThreePhaseAMPS= NULL;
ui_L1AMPS= NULL;
ui_L2AMPS= NULL;
ui_L3AMPS= NULL;
ui_SinglePhaseWINDOW= NULL;
ui_ThreePhasesFullAMPS= NULL;
ui_ThreePhasesFullKVA= NULL;

}
