// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: CurrentMonitor

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_BorderFULL;
extern lv_obj_t *ui_TOPsection;
extern lv_obj_t *ui_Signal_container;
extern lv_obj_t *ui_SignalLOST;
extern lv_obj_t *ui_SignalAntena;
extern lv_obj_t *ui_Signal20percent;
extern lv_obj_t *ui_Signal40percent;
extern lv_obj_t *ui_Signal60percent;
extern lv_obj_t *ui_Signal80percent;
extern lv_obj_t *ui_Signal100percent;
extern lv_obj_t *ui_Battery_container;
extern lv_obj_t *ui_BatteryBODY;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_BatteryTIP;
extern lv_obj_t *ui_UPtime;
extern lv_obj_t *ui_BOTTOMsection;
extern lv_obj_t *ui_BottomINFOFullLoad;
extern lv_obj_t *ui_ButtomINFOSinglePhase;
extern lv_obj_t *ui_Version;
extern lv_obj_t *ui_MGtools;
extern lv_obj_t *ui_ThreePhaseWINDOW;
extern lv_obj_t *ui_ThreePhaseKVA;
extern lv_obj_t *ui_L1KVA;
extern lv_obj_t *ui_L2KVA;
extern lv_obj_t *ui_L3KVA;
extern lv_obj_t *ui_ThreePhaseAMPS;
extern lv_obj_t *ui_L1AMPS;
extern lv_obj_t *ui_L2AMPS;
extern lv_obj_t *ui_L3AMPS;
extern lv_obj_t *ui_SinglePhaseWINDOW;
extern lv_obj_t *ui_ThreePhasesFullAMPS;
extern lv_obj_t *ui_ThreePhasesFullKVA;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

